export const LOADING = 'LOADING';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const GET_USER = 'GET_USER';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const REDIRECT_USER_TO_AUTH = 'REDIRECT_USER_TO_AUTH';
export const  ADD_USER_DETAILS = ' ADD_USER_DETAILS';

export const SHOW_ACTIVATE_MESSAGE = 'SHOW_ACTIVATE_MESSAGE';
export const SHOW_RESET_PWD_MESSAGE = 'SHOW_RESET_PWD_MESSAGE';
export const SEND_ACTIVATION_TOKEN = 'SEND_ACTIVATION_TOKEN';
export const SEND_EMAIL = 'SEND_EMAIL';


