export const LOADING = 'LOADING';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const GET_USER = 'GET_USER';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const REDIRECT_USER_TO_AUTH = 'REDIRECT_USER_TO_AUTH';
export const  ADD_USER_DETAILS = ' ADD_USER_DETAILS';

export const GET_ACTIVATE_EMAIL = 'GET_ACTIVATE_EMAIL';
export const SEND_ACTIVATION_TOKEN = 'SEND_ACTIVATION_TOKEN';
export const SEND_EMAIL = 'SEND_EMAIL';
export const GET_FORGOT_PWD_TOKEN = 'GET_FORGOT_PWD_TOKEN';
export const SEND_NEW_PASSWORD = 'SEND_NEW_PASSWORD';
export const RESET_PWD_SUCCESS = 'RESET_PWD_SUCCESS';


