export const SHOW_SUCCESS_PROFILE_UPDATE= 'SHOW_SUCCESS_PROFILE_UPDATE';
export const CLOSE_SUCCESS_PROFILE_MESSAGE= 'CLOSE_SUCCESS_PROFILE_MESSAGE';

export const SHOW_SUCCESS_PASSWORD_UPDATE= 'SHOW_SUCCESS_PASSWORD_UPDATE';
export const CLOSE_SUCCESS_PASSWORD_MESSAGE= 'CLOSE_SUCCESS_PASSWORD_MESSAGE';

export const LOADING= 'LOADING';

export const LOADING_ORDERS= 'LOADING_ORDERS';
export const GET_ORDERS= 'GET_ORDERS';

export const LOADING_ORDERS_COUNT= 'LOADING_ORDERS_COUNT';
export const GET_ORDERS_COUNT= 'GET_ORDERS_COUNT';




