export const LOADING_CATEGORIES= 'LOADING_CATEGORIES';
export const GET_CATEGORIES= 'GET_CATEGORIES';

export const LOADING_PRODUCTS= 'LOADING_PRODUCTS';
export const GET_BY_CATEGORY= 'GET_BY_CATEGORY';
export const GET_BY_SUB_CATEGORY= 'GET_BY_SUB_CATEGORY';

export const GET_SHOWCASE= 'GET_SHOWCASE';

export const SET_ERROR= 'SET_ERROR';
