export const LOADING_CATEGORIES= 'LOADING_CATEGORIES';
export const GET_CATEGORIES= 'GET_CATEGORIES';

export const LOADING_SUBCATEGORIES= 'LOADING_SUBCATEGORIES';
export const GET_SUBCATEGORIES= 'GET_SUBCATEGORIES';

export const LOADING_PRODUCTS= 'LOADING_PRODUCTS';
export const GET_PRODUCTS= 'GET_PRODUCTS';

export const GET_CATALOG= 'GET_CATALOG';

export const SET_ERROR= 'SET_ERROR';
